# Generated by Django 4.1.3 on 2022-11-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('inventory_num', models.IntegerField()),
                ('number_of_pages', models.IntegerField()),
                ('publusher', models.CharField(max_length=100)),
                ('isbn', models.IntegerField()),
                ('book_type', models.CharField(choices=[('D', 'Електронна'), ('P', 'Паперова')], max_length=1)),
                ('language', models.CharField(max_length=100)),
                ('cover_type', models.CharField(choices=[('S', "М'ягка"), ('H', 'Твёрда')], max_length=1)),
                ('description', models.TextField()),
                ('time_to_read', models.IntegerField()),
                ('pubication_date', models.DateField()),
                ('city_of_publishing', models.CharField(max_length=70)),
                ('additional_type', models.CharField(choices=[('B', 'Книга'), ('J', 'Журнал'), ('N', 'Газета')], default='B', max_length=1)),
                ('publication_type', models.CharField(choices=[('Period', 'Періодичні видання'), ('Books', 'Книги'), ('Dgtl', 'Цифрові видання'), ('Map', 'Карта')], max_length=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='library_app.category')),
            ],
        ),
    ]
