# Generated by Django 4.1.3 on 2022-12-19 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pubication_date',
            new_name='publication_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='pubication_year',
            new_name='publication_year',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publusher',
            new_name='publisher',
        ),
        migrations.AddField(
            model_name='book',
            name='current_reader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('R', 'Reading'), ('W', 'Waiting'), ('A', 'Availible'), ('B', 'Booked')], default='W', max_length=1),
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
