# Generated by Django 4.1.3 on 2022-11-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_alter_book_ubk'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_img_path',
            field=models.CharField(default='', max_length=100, verbose_name='Обкладинка'),
        ),
    ]
