# Generated by Django 4.1.3 on 2022-12-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_book_current_reader_alter_book_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
            preserve_default=False,
        ),
    ]
