# Generated by Django 4.1.3 on 2022-12-14 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_category_color'),
        ('users', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='current_reader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user'),
        ),
    ]
