# Generated by Django 4.1.3 on 2022-12-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('full_address', models.CharField(max_length=100, verbose_name='Aдресса')),
                ('birthday', models.DateField()),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('password', models.CharField(default='zmv8vGcPQC', max_length=77)),
                ('is_disabled_person', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Reader',
                'verbose_name_plural': 'Readers',
            },
        ),
    ]
