# Generated by Django 4.1.3 on 2022-12-14 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_alter_book_current_reader'),
        ('users', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
