# Generated by Django 4.1.3 on 2022-12-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название мероприятия')),
                ('desctiption', models.TextField(verbose_name='Описание')),
                ('date', models.DateField()),
            ],
        ),
    ]
