# Generated by Django 4.1.3 on 2022-12-29 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='desctiption',
            new_name='description',
        ),
    ]
