const additionalFieldsData = b => {
	return (
		[
			{
				label: "Тип документа",
				type: "text",
				value: b.document_type,
				name: "document_type",
			},
			{
				label: "Бібліографічний рівень документа",
				type: "text",
				value: b.bibliografic_document_level,
				name: "bibliografic_document_level",
			},
			{
				label: "Дата ввода документа",
				type: "text",
				value: b.document_entry_date,
				name: "document_entry_date",
			},
			{
				label: "Тип даты публикации",
				type: "text",
				value: b.pubication_date_type,
				name: "pubication_date_type",
			},
			{
				label: "Коды наличия типов иллюстраций",
				type: "text",
				value: b.illustration_type_availability_codes,
				name: "illustration_type_availability_codes",
			},
			{
				label: "Код возрастной ориентации",
				type: "text",
				value: b.age_orientation_code,
				name: "age_orientation_code",
			},
			{
				label: "Код типа материала",
				type: "text",
				value: b.material_type_code,
				name: "material_type_code",
			},
			{
				label: "Коды типа документа",
				type: "text",
				value: b.document_type_codes,
				name: "document_type_codes",
			},
			{
				label: "Статус правительственной публикаций",
				type: "text",
				value: b.government_publication_status,
				name: "government_publication_status",
			},
			{
				label: "Признак публикации конференции",
				type: "text",
				value: b.is_conference_publishing,
				name: "is_conference_publishing",
			},
			{
				label: "Признак юбилейного издания",
				type: "text",
				value: b.is_jubilee,
				name: "is_jubilee",
			},
			{
				label: "Ознака наявності покажчиків",
				type: "text",
				value: b.is_pointers,
				name: "is_pointers",
			},
			{
				label: "Main entry?",
				type: "text",
				value: b.is_main_entry,
				name: "is_main_entry",
			},
			{
				label: "Ознака мистецтв. літератури",
				type: "text",
				value: b.is_arts_literature,
				name: "is_arts_literature",
			},
			{
				label: "Код типу біографії",
				type: "text",
				value: b.biografy_type_code,
				name: "biografy_type_code",
			},
			{
				label: "Код мови документа",
				type: "text",
				value: b.document_lang_code,
				name: "document_lang_code",
			},
			{
				label: "Код організації, яка створила запис",
				type: "text",
				value: b.organization_that_created_rec_code,
				name: "organization_that_created_rec_code",
			},
			{
				label: "Ціна",
				type: "text",
				value: b.price,
				name: "price",
			},
			{
				label: "Помилковий ISBN",
				type: "text",
				value: b.invalid_isbn,
				name: "invalid_isbn",
			},
			{
				label: "Код бібліотеки, створеного запису",
				type: "text",
				value: b.library_code,
				name: "library_code",
			},
			{
				label: "Код мови каталогізації",
				type: "text",
				value: b.catalization_lang_code,
				name: "catalization_lang_code",
			},
			{
				label: "Відповідальний",
				type: "text",
				value: b.responsible,
				name: "responsible",
			},
			{
				label: "Переклад",
				type: "text",
				value: b.translation,
				name: "translation",
			},
			{
				label: "Код мови тексту",
				type: "text",
				value: b.text_lang_code,
				name: "text_lang_code",
			},
			{
				label: "Код мови передмови",
				type: "text",
				value: b.preface_lang_code,
				name: "preface_lang_code",
			},
			{
				label: "Код мови змісту",
				type: "text",
				value: b.context_lang_code,
				name: "context_lang_code",
			},
			{
				label: "Код мови оригіналу",
				type: "text",
				value: b.original_lang_code,
				name: "original_lang_code",
			},
			{
				label: "Код країни",
				type: "text",
				value: b.country_code,
				name: "country_code",
			},
			{
				label: "Iндекс УДК",
				type: "text",
				value: b.udk_index,
				name: "udk_index",
			},
			{
				label: "УДК",
				type: "text",
				value: b.udk,
				name: "udk",
			},
			{
				label: "Джерело класифікації",
				type: "text",
				value: b.classification_source,
				name: "classification_source",
			},
			{
				label: "Поличний шифр",
				type: "text",
				value: b.shelf_cipher,
				name: "shelf_cipher",
			},
			{
				label: "Національний код бібліотеки",
				type: "text",
				value: b.national_library_code,
				name: "national_library_code",
			},
			{
				label: "Кат. індекси",
				type: "text",
				value: b.category_indexes,
				name: "category_indexes",
			},
			{
				label: "Сигла зберігання",
				type: "text",
				value: b.storage_symbol,
				name: "storage_symbol",
			},
			{
				label: "Фоpмат",
				type: "text",
				value: b.book_format,
				name: "book_format",
			},
			{
				label: "Номер фонду",
				type: "text",
				value: b.fond_number,
				name: "fond_number",
			},
			{
				label: "Авторський знак",
				type: "text",
				value: b.copyright_sign,
				name: "copyright_sign",
			},
			{
				label: "Індекси / коди",
				type: "text",
				value: b.indexes,
				name: "indexes",
			},
			{
				label: "Індекс ББК",
				type: "text",
				value: b.indexes_bbk,
				name: "indexes_bbk",
			},
			{
				label: "Джерело класифікації",
				type: "text",
				value: b.rank,
				name: "rank",
			},
			// {
			// 	label: "Династичний номер",
			// 	type: "text",
			// 	value: b.property,
			// 	name: "property",
			// },
			// {
			// 	label: "Титул (звання)",
			// 	type: "text",
			// 	value: b.property,
			// 	name: "property",
			// },
			{
				label: "Організація / юрисдикція",
				type: "text",
				value: b.organisation,
				name: "organisation",
			},
			{
				label: "Підпорядкована одиниця",
				type: "text",
				value: b.subordinate_unit,
				name: "subordinate_unit",
			},
			{
				label: "Номер організації",
				type: "text",
				value: b.section_number,
				name: "section_number",
			},
			// {
			// 	label: "Місце заходу",
			// 	type: "text",
			// 	value: b.property,
			// 	name: "property",
			// },
			// {
			// 	label: "Дата заходу",
			// 	type: "text",
			// 	value: b.property,
			// 	name: "property",
			// },
			// {
			// 	label: "Соподчиненная одиниця",
			// 	type: "text",
			// 	value: b.property,
			// 	name: "property",
			// },
			// {
			// 	label: "№ частини / секції",
			// 	type: "text",
			// 	value: b.property,
			// 	name: "property",
			// },
			{
				label: "Уніфікований заголовок",
				type: "text",
				value: b.unified_title,
				name: "unified_title",
			},
			{
				label: "Iндикатор",
				type: "text",
				value: b.indicator,
				name: "indicator",
			},
			{
				label: "Незначущі символи",
				type: "text",
				value: b.minor_characters,
				name: "minor_characters",
			},
			// {
			// 	label: "№ частини / розділу",
			// 	type: "text",
			// 	value: b.property,
			// 	name: "property",
			// },
			{
				label: "Переклад назви",
				type: "text",
				value: b.title_translation,
				name: "title_translation",
			},
			// {
			// 	label: "Назва",
			// 	type: "text",
			// 	value: b.property,
			// 	name: "property",
			// },
			{
				label: "Продовження назви",
				type: "text",
				value: b.title_continuation,
				name: "title_continuation",
			},
			{
				label: "Відповідальність",
				type: "text",
				value: b.responsibility,
				name: "responsibility",
			},
			// {
			// 	label: "Дати твори",
			// 	type: "text",
			// 	value: b.property,
			// 	name: "property",
			// },
			{
				label: "Тип запису / Звукозапис",
				type: "text",
				value: b.recording_type,
				name: "recording_type",
			},
			{
				label: "Паралельна назва",
				type: "text",
				value: b.parllel_title,
				name: "parllel_title",
			},
			{
				label: "Тип заголовку",
				type: "text",
				value: b.header_types,
				name: "header_types",
			},
			{
				label: "Основний заголовок",
				type: "text",
				value: b.main_header,
				name: "main_header",
			},
			{
				label: "Осн. Відомості про видання",
				type: "text",
				value: b.main_publication_info,
				name: "main_publication_info",
			},
			{
				label: "Доп. Відомості про видання",
				type: "text",
				value: b.additional_publication_info,
				name: "additional_publication_info",
			},
			{
				label: "Місце видання",
				type: "text",
				value: b.publication_city,
				name: "publication_city",
			},
			// {
			// 	label: "Видавництво",
			// 	type: "text",
			// 	value: b.property,
			// 	name: "property",
			// },
			{
				label: "Дата видання",
				type: "text",
				value: b.publish_date,
				name: "publish_date",
			},
			{
				label: "Обсяг",
				type: "text",
				value: b.amount,
				name: "amount",
			},
			{
				label: "Іл. / Тип воспроизв",
				type: "text",
				value: b.playback_type,
				name: "playback_type",
			},
			{
				label: "Формат",
				type: "text",
				value: b.another_format,
				name: "another_format",
			},
			{
				label: "Сопров. матер.",
				type: "text",
				value: b.additional_materials,
				name: "additional_materials",
			},
			{
				label: "Серія",
				type: "text",
				value: b.serial,
				name: "serial",
			},
			{
				label: "Номер частини",
				type: "text",
				value: b.part_section_number,
				name: "part_section_number",
			},
			{
				label: "Назва частини",
				type: "text",
				value: b.part_section_title,
				name: "part_section_title",
			},
			{
				label: "№ томи, номера",
				type: "text",
				value: b.number_volumes,
				name: "number_volumes",
			},
			{
				label: "ISSN",
				type: "text",
				value: b.issn,
				name: "issn",
			},
			// {
			// 	label: "Тип прямуючи.",
			// 	type: "text",
			// 	value: b.property,
			// 	name: "property",
			// },
			{
				label: "Формат. зміст",
				type: "text",
				value: b.content_format,
				name: "content_format",
			},
			{
				label: "Примітки про посилання",
				type: "text",
				value: b.reference_notes,
				name: "reference_notes",
			},
			{
				label: "Анотація",
				type: "text",
				value: b.annotation,
				name: "annotation",
			},
			{
				label: "Прим. про целев. призначення",
				type: "text",
				value: b.destination_note,
				name: "destination_note",
			},
			{
				label: "Рівень",
				type: "text",
				value: b.level,
				name: "level",
			},
			{
				label: "Рубрикатор",
				type: "text",
				value: b.rubricator,
				name: "rubricator",
			},
			{
				label: "Основна рубр",
				type: "text",
				value: b.main_heading,
				name: "main_heading",
			},
			{
				label: "Осн. подрубр",
				type: "text",
				value: b.main_subheading,
				name: "main_subheading",
			},
			{
				label: "Місце друкування",
				type: "text",
				value: b.place_of_printing,
				name: "place_of_printing",
			},
			{
				label: "Бібліографія",
				type: "text",
				value: b.bibliografic,
				name: "bibliografic",
			},
			{
				label: "Хронол. подрубр",
				type: "text",
				value: b.hronological_subheading,
				name: "hronological_subheading",
			},
			{
				label: "Гео. подрубр.",
				type: "text",
				value: b.geografical_subheading,
				name: "geografical_subheading",
			},
			{
				label: "Ключові слова",
				type: "text",
				value: b.keywoards,
				name: "keywoards",
			},
			{
				label: "Iнші автори",
				type: "text",
				value: b.other_authors,
				name: "other_authors",
			},
			{
				label: "Династичний номер",
				type: "text",
				value: b.dynastic_number,
				name: "dynastic_number",
			},
			{
				label: "Код авторського ставлення",
				type: "text",
				value: b.author_attitude_code,
				name: "author_attitude_code",
			},
			{
				label: "Iнші організації",
				type: "text",
				value: b.other_organisations,
				name: "other_organisations",
			},
			{
				label: "Iнші заходи",
				type: "text",
				value: b.other_measures,
				name: "other_measures",
			},
			{
				label: "Місцезнаходження",
				type: "text",
				value: b.location,
				name: "location",
			},
			{
				label: "Фонд",
				type: "text",
				value: b.fund,
				name: "fund",
			},
			// {
			// 	label: "Авторський знак",
			// 	type: "text",
			// 	value: b.property,
			// 	name: "property",
			// },
			// {
			// 	label: "Поличний шифр",
			// 	type: "text",
			// 	value: b.property,
			// 	name: "property",
			// },
			{
				label: "Спосіб (тип) доступу",
				type: "text",
				value: b.access_method,
				name: "access_method",
			},
			{
				label: "Ім'я сервера (HostName)",
				type: "text",
				value: b.host_name,
				name: "host_name",
			},
			{
				label: "Місцезнаходження сервера",
				type: "text",
				value: b.server_location,
				name: "server_location",
			},
			{
				label: "Персоналія",
				type: "text",
				value: b.personnel,
				name: "personnel",
			},
			{
				label: "Коди країни",
				type: "text",
				value: b.country_codes,
				name: "country_codes",
			},
			{
				label: "Спонсори",
				type: "text",
				value: b.sponsors,
				name: "sponsors",
			},
			{
				label: "Категорія книг",
				type: "text",
				value: b.book_category,
				name: "book_category",
			},
		]
	);
};

export default additionalFieldsData;