const additionalFieldsData = b => {
	return (
		[
			{
				label: "Тип документа",
				type: "text",
				value: b.documentType,
				name: "documentType",
			},
			{
				label: "Бібліографічний рівень документа",
				type: "text",
				value: b.bibliographicLevel,
				name: "bibliographicLevel",
			},
			{
				label: "Дата ввода документа",
				type: "text",
				value: b.documentEntryDate,
				name: "documentEntryDate",
			},
			{
				label: "Тип даты публикации",
				type: "text",
				value: b.publicationDateType,
				name: "publicationDateType",
			},
			{
				label: "Коды наличия типов иллюстраций",
				type: "text",
				value: b.illustrationTypeAvailabilityCodes,
				name: "illustrationTypeAvailabilityCodes",
			},
			{
				label: "Код возрастной ориентации",
				type: "text",
				value: b.ageOrientationCode,
				name: "ageOrientationCode",
			},
			{
				label: "Код типа материала",
				type: "text",
				value: b.materialTypeCode,
				name: "materialTypeCode",
			},
			{
				label: "Коды типа документа",
				type: "text",
				value: b.documentTypeCodes,
				name: "documentTypeCodes",
			},
			{
				label: "Статус правительственной публикаций",
				type: "text",
				value: b.statusOfGovernmentPublications,
				name: "statusOfGovernmentPublications",
			},
			{
				label: "Признак публикации конференции",
				type: "text",
				value: b.conferencePublishingFlag,
				name: "conferencePublishingFlag",
			},
			{
				label: "Признак юбилейного издания",
				type: "text",
				value: b.anniversaryEditionSign,
				name: "anniversaryEditionSign",
			},
			{
				label: "Ознака наявності покажчиків",
				type: "text",
				value: b.signOfPresenceOfIndicators,
				name: "signOfPresenceOfIndicators",
			},
			{
				label: "Main entry?",
				type: "text",
				value: b.mainEntry,
				name: "mainEntry",
			},
			{
				label: "Ознака мистецтв. літератури",
				type: "text",
				value: b.mysticSign_Literature,
				name: "mysticSign_Literature",
			},
			{
				label: "Код типу біографії",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Код мови документа",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Код організації, яка створила запис",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Ціна",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Помилковий ISBN",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Код бібліотеки, створеного запису",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Код мови каталогізації",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Відповідальний",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Переклад",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Код мови тексту",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Код мови передмови",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Код мови змісту",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Код мови оригіналу",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Код країни",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Iндекс УДК",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "УДК",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Джерело класифікації",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Поличний шифр",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Національний код бібліотеки",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Кат. індекси",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Сигла зберігання",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Фоpмат",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Номер фонду",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Авторський знак",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Індекси / коди",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Індекс ББК",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Джерело класифікації",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Династичний номер",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Титул (звання)",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Організація / юрисдикція",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Підпорядкована одиниця",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Номер організації",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Місце заходу",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Дата заходу",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Соподчиненная одиниця",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "№ частини / секції",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Уніфікований заголовок",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Iндикатор",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Незначущі символи",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "№ частини / розділу",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Переклад назви",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Назва",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Продовження назви",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Відповідальність",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Дати твори",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Тип запису / Звукозапис",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Паралельна назва",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Тип заголовку",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Основний заголовок",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Осн. Відомості про видання",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Доп. Відомості про видання",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Місце видання",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Видавництво",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Дата видання",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Обсяг",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Іл. / Тип воспроизв",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Формат",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Сопров. матер.",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Серія",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Номер частини",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Назва частини",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "№ томи, номера",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "ISSN",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Тип прямуючи.",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Формат. зміст",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Примітки про посилання",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Анотація",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Прим. про целев. призначення",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Рівень",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Рубрикатор",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Основна рубр",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Осн. подрубр",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Місце друкування",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Бібліографія",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Хронол. подрубр",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Гео. подрубр.",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Ключові слова",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Ключові слова",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Iнші автори",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Династичний номер",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Код авторського ставлення",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Iнші організації",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Iнші заходи",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Місцезнаходження",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Фонд",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Авторський знак",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Поличний шифр",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Спосіб (тип) доступу",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Ім'я сервера (HostName)",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Персоналія",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Коди країни",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Спонсори",
				type: "text",
				value: b.property,
				name: "property",
			},
			{
				label: "Категорія книг",
				type: "text",
				value: b.property,
				name: "property",
			},
		]
	);
};

export default additionalFieldsData;