# Generated by Django 4.1.3 on 2022-12-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='home_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Робоча адресса'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_disabled_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Домашня адресса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='qJmHfRX', max_length=130),
        ),
    ]
