# Generated by Django 4.1.3 on 2022-12-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='QE6xE9Y', max_length=130),
        ),
    ]
